=begin
#dataintegrationapi

#Easily and directly query database backup files, convert into other file formats.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.14

=end

module CloudmersiveDataintegrationApiClient
  VERSION = '2.0.2'
end
