=begin
#dataintegrationapi

#Easily and directly query database backup files, convert into other file formats.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.14

=end

# Common files
require 'cloudmersive-dataintegration-api-client/api_client'
require 'cloudmersive-dataintegration-api-client/api_error'
require 'cloudmersive-dataintegration-api-client/version'
require 'cloudmersive-dataintegration-api-client/configuration'

# Models
require 'cloudmersive-dataintegration-api-client/models/mssql_bak_enumerate_tables_result'
require 'cloudmersive-dataintegration-api-client/models/mssql_table'

# APIs
require 'cloudmersive-dataintegration-api-client/api/backup_convert_api'

module CloudmersiveDataintegrationApiClient
  class << self
    # Customize default settings for the SDK using block.
    #   CloudmersiveDataintegrationApiClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
